"""Build a macOS .app bundle so the assistant owns its own TCC permissions.

Why this exists: macOS attributes Automation, Microphone and Screen Recording
consent to the **responsible process** — the thing that launched the code, not
the code itself. Run `python -m assistant` from a terminal and the grants
attach to that terminal. During development that meant the assistant was
borrowing Claude Code's permissions, which is both wrong in production and
impossible for a user to reason about: they cannot grant, review, or revoke
permissions for "the assistant" because macOS has never seen one.

A bundle with its own CFBundleIdentifier gives the assistant a stable identity
that appears by name in System Settings > Privacy & Security.

Build:  python -m appbundle.build_app
"""
from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

BUNDLE_ID = "com.glimmer.assistant"
VERSION = "0.1.0"
EXECUTABLE = "glimmer-assistant"

# These strings are shown verbatim in the consent dialog and are the only
# context the user gets for an irreversible-feeling decision. Say why, not what.
MIC_USAGE = (
    "Glimmer Assistant records audio only between Start and Stop Listening, "
    "so it can transcribe your request on this Mac. Audio is never uploaded."
)
APPLE_EVENTS_USAGE = (
    "Glimmer Assistant controls Mail, Calendar and System Events to read your "
    "messages and events and to act on requests you make out loud. Every action "
    "that sends or changes something asks you first."
)


def _launcher_script(python: str, module: str, args: list[str]) -> str:
    # Paths are quoted: a venv under ~/Library/Application Support, or any user
    # directory with a space, would otherwise split into separate words.
    argv = " ".join(f'"{a}"' for a in args)
    return (
        "#!/bin/sh\n"
        "# Generated by appbundle/build_app.py — do not edit in place.\n"
        "# exec keeps the bundle as the process macOS attributes TCC grants to;\n"
        "# spawning a child would hand the identity to the shell instead.\n"
        f'exec "{python}" -m {module} {argv}\n'
    )


def build_bundle(
    app_path: Path,
    python: str | None = None,
    module: str = "assistant",
    args: list[str] | None = None,
    sign: bool = False,
) -> Path:
    app_path = Path(app_path)
    python = python or sys.executable
    args = list(args if args is not None else ["--voice"])

    contents = app_path / "Contents"
    macos = contents / "MacOS"
    # Remove first so a rebuild cannot leave a stale executable behind that the
    # new Info.plist no longer names.
    if app_path.exists():
        shutil.rmtree(app_path)
    macos.mkdir(parents=True)

    info = {
        "CFBundleName": "Glimmer Assistant",
        "CFBundleDisplayName": "Glimmer Assistant",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": EXECUTABLE,
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "CFBundlePackageType": "APPL",
        "LSMinimumSystemVersion": "13.0",
        # Background agent: a push-to-talk assistant should not own a Dock icon
        # or steal focus when it starts.
        "LSUIElement": True,
        "NSMicrophoneUsageDescription": MIC_USAGE,
        "NSAppleEventsUsageDescription": APPLE_EVENTS_USAGE,
    }
    (contents / "Info.plist").write_bytes(plistlib.dumps(info))

    launcher = macos / EXECUTABLE
    launcher.write_text(_launcher_script(python, module, args))
    launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    if sign:
        _adhoc_sign(app_path)
    return app_path


def _adhoc_sign(app_path: Path) -> None:
    """Ad-hoc sign so TCC has a stable code identity to bind grants to.

    Unsigned bundles get their grants invalidated whenever the executable
    changes, which shows up as permissions mysteriously needing to be
    re-granted. Ad-hoc signing is enough for local use; a Developer ID
    signature would be needed for distribution.
    """
    try:
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-", str(app_path)],
            check=True, capture_output=True, text=True,
        )
    except FileNotFoundError:
        print("warning: codesign not found; bundle left unsigned", file=sys.stderr)
    except subprocess.CalledProcessError as e:
        print(f"warning: codesign failed: {e.stderr.strip()}", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(Path("dist") / "Glimmer Assistant.app"),
        help="where to write the bundle",
    )
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--text-mode", action="store_true",
                        help="launch in text mode instead of voice")
    parser.add_argument("--no-sign", action="store_true")
    ns = parser.parse_args(argv)

    out = Path(ns.out).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    app = build_bundle(
        out,
        python=ns.python,
        args=[] if ns.text_mode else ["--voice"],
        sign=not ns.no_sign,
    )
    print(f"built {app}")
    print(f"  identifier: {BUNDLE_ID}")
    print(f"  interpreter: {ns.python}")
    print("\nLaunch it once so macOS registers it:")
    print(f'  open "{app}"')
    print("\nThen grant it permissions under System Settings > Privacy & Security")
    print("(Microphone, Automation, and Screen Recording if you want screenshots).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
